dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=driverkit
    - RUSTFLAGS='-D warnings'

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true
  - rustup component add rustfmt-preview --toolchain nightly

before_script:
  - sudo sysctl -w vm.nr_hugepages=5
  - sudo mkdir -p /mnt/huge
  - sudo mount -t hugetlbfs nodev /mnt/huge

script:
  - bash ci/script.sh
  - cargo +nightly fmt --version
  - cargo +nightly fmt --package driverkit -- --check

after_script: set +e

branches:
  except:
    - staging.tmp
    - trying.tmp

notifications:
  email:
    on_success: never
