[package]
name = "driverkit"
version = "0.2.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]
readme = "README.md"
description = "A driver framework defining standard types and interfaces for writing device drivers."
keywords = ["driver", "os", "framework"]
repository = "https://github.com/gz/rust-driverkit"
license = "MIT/Apache-2.0"

[target.x86_64-unknown-linux-gnu.dependencies]
mmap = "0.1.*"
libc = "0.2.*"

[dependencies]
byteorder = "0.5"
x86 = "0.11.*"

[[bin]]
name = "testdrive"
path = "src/bin/testdrive.rs"
