[package]
name = "driverkit"
version = "0.1.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

[target.x86_64-unknown-linux-gnu.dependencies]
mmap = "*"
libc = "*"

[dependencies]
#num = "0.1.32"
byteorder = "0.5"

[[bin]]
name = "testdrive"
path = "src/bin/testdrive.rs"
